"""empty message

Revision ID: 0a65eda1d4e2
Revises: 205aca3fd848
Create Date: 2022-01-26 18:13:37.070859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a65eda1d4e2'
down_revision = '205aca3fd848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('First_Name', sa.String(length=50), nullable=True),
    sa.Column('Last_Name', sa.String(length=50), nullable=True),
    sa.Column('Phone_No', sa.String(length=15), nullable=True),
    sa.Column('Email', sa.String(length=70), nullable=True),
    sa.Column('Subject', sa.String(length=50), nullable=True),
    sa.Column('Date', sa.String(length=50), nullable=True),
    sa.Column('StartTime', sa.String(length=30), nullable=True),
    sa.Column('EndTime', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preset')
    # ### end Alembic commands ###
