"""empty message

Revision ID: 205aca3fd848
Revises: 704c511eac8e
Create Date: 2022-01-26 17:46:54.356328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205aca3fd848'
down_revision = '704c511eac8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('First_Name', sa.String(length=50), nullable=True),
    sa.Column('Last_Name', sa.String(length=50), nullable=True),
    sa.Column('Phone_No', sa.String(length=15), nullable=True),
    sa.Column('Email', sa.String(length=70), nullable=True),
    sa.Column('Subject', sa.String(length=50), nullable=True),
    sa.Column('StartTime', sa.String(length=30), nullable=True),
    sa.Column('EndTime', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preset')
    # ### end Alembic commands ###
