"""empty message

Revision ID: ed997072ca89
Revises: efe0a4d32c34
Create Date: 2022-01-26 16:39:03.463390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed997072ca89'
down_revision = 'efe0a4d32c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Subject', sa.String(length=50), nullable=True),
    sa.Column('StartTime', sa.String(length=25), nullable=True),
    sa.Column('EndTime', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preset')
    # ### end Alembic commands ###
